### PR TITLE
Nodejs

### PR DESCRIPTION
**Pull request by justincy**
https://github.com/rootsdev/familysearch-javascript-sdk/issues/8

Used [q](https://github.com/kriskowal/q) for promises and [request](https://github.com/request/request) for http.

### CODE REVIEW

**Comment by justincy** [comment]
This isn't ready to merge yet. Still some things to do. The hard stuff is done though. Took forever to figure out how to get RequireJS to work both in node, tests, and the resulting build.

* Authentication doesn't work.
* Will need to modify how the access_token is stored.

**Comment by justincy** [comment]
For the access_token storage, it doesn't make much sense in node. If you want to save the access_token it should be handled externally by your app and then you should initialize the SDK with the token.

**Comment by justincy** [comment]
Regarding authentication, what would support look like? The SDK can't do the normal OAuth2 dance like we do in the browser. A developer would have to handle that themselves and just pass the access_token to the SDK when it's all done. I'll probably have the SDK throw an error if you attempt to start the normal OAuth flow in node.

The SDK already supports the [password grant](https://familysearch.org/developers/docs/api/authentication/Obtain_Access_Token_with_Username_and_Password_usecase) flow with [`getAccessTokenForMobile()`](http://rootsdev.org/familysearch-javascript-sdk/#/api/authentication.functions:getAccessTokenForMobile). That should work as-is in node.

**Comment by DallanQ** [comment]
My thinking also was that the developer would pass in the OAuth token in node.js mode. It's one of the parameters in the init call.

**Comment by justincy** [comment]
I'm done with this. I wouldn't be surprised if there are bugs, but if they exist they'll most likely be in the node.js environment as opposed to the browser.

I'll probably wait to merge this until I have a better idea of how much work #42 (supporting multiple instances) will be.

**Pull request merged**
